#include "qsdlkeyboardmap.h"

QSdlKeyboardMap::QSdlKeyboardMap(){
	keyMap.clear();
	keyMap.insert(SDLK_UNKNOWN, Qt::Key_unknown);
	keyMap.insert(SDLK_FIRST, Qt::Key_unknown);
	keyMap.insert(SDLK_BACKSPACE, Qt::Key_Backspace);
	keyMap.insert(SDLK_TAB, Qt::Key_Tab);
	keyMap.insert(SDLK_CLEAR, Qt::Key_Clear);
	keyMap.insert(SDLK_RETURN, Qt::Key_Return);
	keyMap.insert(SDLK_PAUSE, Qt::Key_Pause);
	keyMap.insert(SDLK_ESCAPE, Qt::Key_Escape);
	keyMap.insert(SDLK_SPACE, Qt::Key_Space);
	keyMap.insert(SDLK_EXCLAIM, Qt::Key_Exclam);
	keyMap.insert(SDLK_QUOTEDBL, Qt::Key_QuoteDbl);
	keyMap.insert(SDLK_HASH, Qt::Key_NumberSign);
	keyMap.insert(SDLK_DOLLAR, Qt::Key_Dollar);
	keyMap.insert(SDLK_AMPERSAND, Qt::Key_Ampersand);
	keyMap.insert(SDLK_QUOTE, Qt::Key_Apostrophe);
	keyMap.insert(SDLK_LEFTPAREN, Qt::Key_ParenLeft);
	keyMap.insert(SDLK_RIGHTPAREN, Qt::Key_ParenRight);
	keyMap.insert(SDLK_ASTERISK, Qt::Key_Asterisk);
	keyMap.insert(SDLK_PLUS, Qt::Key_Plus);
	keyMap.insert(SDLK_COMMA, Qt::Key_Comma);
	keyMap.insert(SDLK_MINUS, Qt::Key_Minus);
	keyMap.insert(SDLK_PERIOD, Qt::Key_Period);
	keyMap.insert(SDLK_SLASH, Qt::Key_Slash);
	keyMap.insert(SDLK_0, Qt::Key_0 );
	keyMap.insert(SDLK_1, Qt::Key_1 );
	keyMap.insert(SDLK_2, Qt::Key_2 );
	keyMap.insert(SDLK_3, Qt::Key_3 );
	keyMap.insert(SDLK_4, Qt::Key_4 );
	keyMap.insert(SDLK_5, Qt::Key_5 );
	keyMap.insert(SDLK_6, Qt::Key_6 );
	keyMap.insert(SDLK_7, Qt::Key_7 );
	keyMap.insert(SDLK_8, Qt::Key_8 );
	keyMap.insert(SDLK_9, Qt::Key_9 );
	keyMap.insert(SDLK_COLON, Qt::Key_Colon );
	keyMap.insert(SDLK_SEMICOLON, Qt::Key_Semicolon );
	keyMap.insert(SDLK_LESS, Qt::Key_Less );
	keyMap.insert(SDLK_EQUALS, Qt::Key_Equal );
	keyMap.insert(SDLK_GREATER, Qt::Key_Greater );
	keyMap.insert(SDLK_QUESTION, Qt::Key_Question );
	keyMap.insert(SDLK_AT, Qt::Key_At );
	keyMap.insert(SDLK_LEFTBRACKET, Qt::Key_BracketLeft );
	keyMap.insert(SDLK_BACKSLASH, Qt::Key_Backslash );
	keyMap.insert(SDLK_RIGHTBRACKET, Qt::Key_BracketRight );
	keyMap.insert(SDLK_CARET, Qt::Key_AsciiCircum );
	keyMap.insert(SDLK_UNDERSCORE, Qt::Key_Underscore );
	keyMap.insert(SDLK_BACKQUOTE, Qt::Key_QuoteLeft );
	keyMap.insert(SDLK_a, Qt::Key_A );
	keyMap.insert(SDLK_b, Qt::Key_B );
	keyMap.insert(SDLK_c, Qt::Key_C );
	keyMap.insert(SDLK_d, Qt::Key_D );
	keyMap.insert(SDLK_e, Qt::Key_E );
	keyMap.insert(SDLK_f, Qt::Key_F );
	keyMap.insert(SDLK_g, Qt::Key_G );
	keyMap.insert(SDLK_h, Qt::Key_H );
	keyMap.insert(SDLK_i, Qt::Key_I );
	keyMap.insert(SDLK_j, Qt::Key_J );
	keyMap.insert(SDLK_k, Qt::Key_K );
	keyMap.insert(SDLK_l, Qt::Key_L );
	keyMap.insert(SDLK_m, Qt::Key_M );
	keyMap.insert(SDLK_n, Qt::Key_N );
	keyMap.insert(SDLK_o, Qt::Key_O );
	keyMap.insert(SDLK_p, Qt::Key_P );
	keyMap.insert(SDLK_q, Qt::Key_Q );
	keyMap.insert(SDLK_r, Qt::Key_R );
	keyMap.insert(SDLK_s, Qt::Key_S );
	keyMap.insert(SDLK_t, Qt::Key_T );
	keyMap.insert(SDLK_u, Qt::Key_U );
	keyMap.insert(SDLK_v, Qt::Key_V );
	keyMap.insert(SDLK_w, Qt::Key_W );
	keyMap.insert(SDLK_x, Qt::Key_X );
	keyMap.insert(SDLK_y, Qt::Key_Y );
	keyMap.insert(SDLK_z, Qt::Key_Z );
	keyMap.insert(SDLK_DELETE, Qt::Key_Delete );
	keyMap.insert(SDLK_WORLD_0, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_1, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_2, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_3, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_4, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_5, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_6, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_7, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_8, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_9, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_10, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_11, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_12, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_13, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_14, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_15, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_16, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_17, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_18, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_19, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_20, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_21, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_22, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_23, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_24, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_25, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_26, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_27, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_28, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_29, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_30, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_31, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_32, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_33, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_34, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_35, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_36, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_37, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_38, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_39, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_40, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_41, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_42, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_43, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_44, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_45, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_46, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_47, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_48, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_49, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_50, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_51, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_52, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_53, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_54, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_55, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_56, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_57, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_58, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_59, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_60, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_61, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_62, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_63, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_64, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_65, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_66, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_67, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_68, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_69, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_70, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_71, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_72, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_73, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_74, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_75, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_76, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_77, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_78, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_79, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_80, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_81, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_82, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_83, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_84, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_85, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_86, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_87, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_88, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_89, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_90, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_91, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_92, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_93, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_94, Qt::Key_unknown );
	keyMap.insert(SDLK_WORLD_95, Qt::Key_unknown );
	keyMap.insert(SDLK_KP0, Qt::Key_0 );
	keyMap.insert(SDLK_KP1, Qt::Key_1 );
	keyMap.insert(SDLK_KP2, Qt::Key_2 );
	keyMap.insert(SDLK_KP3, Qt::Key_3 );
	keyMap.insert(SDLK_KP4, Qt::Key_4 );
	keyMap.insert(SDLK_KP5, Qt::Key_5 );
	keyMap.insert(SDLK_KP6, Qt::Key_6 );
	keyMap.insert(SDLK_KP7, Qt::Key_7 );
	keyMap.insert(SDLK_KP8, Qt::Key_8 );
	keyMap.insert(SDLK_KP9, Qt::Key_9 );
	keyMap.insert(SDLK_KP_PERIOD, Qt::Key_Period );
	keyMap.insert(SDLK_KP_DIVIDE, Qt::Key_Slash );
	keyMap.insert(SDLK_KP_MULTIPLY, Qt::Key_Asterisk );
	keyMap.insert(SDLK_KP_MINUS, Qt::Key_Minus );
	keyMap.insert(SDLK_KP_PLUS, Qt::Key_Plus );
	keyMap.insert(SDLK_KP_ENTER, Qt::Key_Enter );
	keyMap.insert(SDLK_KP_EQUALS, Qt::Key_unknown );
	keyMap.insert(SDLK_UP, Qt::Key_Up );
	keyMap.insert(SDLK_DOWN, Qt::Key_Down );
	keyMap.insert(SDLK_RIGHT, Qt::Key_Right );
	keyMap.insert(SDLK_LEFT, Qt::Key_Left );
	keyMap.insert(SDLK_INSERT, Qt::Key_Insert );
	keyMap.insert(SDLK_HOME, Qt::Key_Home );
	keyMap.insert(SDLK_END, Qt::Key_End );
	keyMap.insert(SDLK_PAGEUP, Qt::Key_PageUp );
	keyMap.insert(SDLK_PAGEDOWN, Qt::Key_PageDown );
	keyMap.insert(SDLK_F1, Qt::Key_F1 );
	keyMap.insert(SDLK_F2, Qt::Key_F2 );
	keyMap.insert(SDLK_F3, Qt::Key_F3 );
	keyMap.insert(SDLK_F4, Qt::Key_F4 );
	keyMap.insert(SDLK_F5, Qt::Key_F5 );
	keyMap.insert(SDLK_F6, Qt::Key_F6 );
	keyMap.insert(SDLK_F7, Qt::Key_F7 );
	keyMap.insert(SDLK_F8, Qt::Key_F8 );
	keyMap.insert(SDLK_F9, Qt::Key_F9 );
	keyMap.insert(SDLK_F10, Qt::Key_F10 );
	keyMap.insert(SDLK_F11, Qt::Key_F11 );
	keyMap.insert(SDLK_F12, Qt::Key_F12 );
	keyMap.insert(SDLK_F13, Qt::Key_F13 );
	keyMap.insert(SDLK_F14, Qt::Key_F14 );
	keyMap.insert(SDLK_F15, Qt::Key_F15 );
	keyMap.insert(SDLK_NUMLOCK, Qt::Key_NumLock );
	keyMap.insert(SDLK_CAPSLOCK, Qt::Key_CapsLock );
	keyMap.insert(SDLK_SCROLLOCK, Qt::Key_ScrollLock );
	keyMap.insert(SDLK_RSHIFT, Qt::Key_Shift );
	keyMap.insert(SDLK_LSHIFT, Qt::Key_Shift );
	keyMap.insert(SDLK_RCTRL, Qt::Key_Control );
	keyMap.insert(SDLK_LCTRL, Qt::Key_Control );
	keyMap.insert(SDLK_RALT, Qt::Key_Alt );
	keyMap.insert(SDLK_LALT, Qt::Key_Alt );
	keyMap.insert(SDLK_RMETA, Qt::Key_Meta );
	keyMap.insert(SDLK_LMETA, Qt::Key_Meta );
	keyMap.insert(SDLK_LSUPER, Qt::Key_Meta );
	keyMap.insert(SDLK_RSUPER, Qt::Key_Meta );
	keyMap.insert(SDLK_MODE, Qt::Key_unknown );
	keyMap.insert(SDLK_COMPOSE, Qt::Key_unknown );
	keyMap.insert(SDLK_HELP, Qt::Key_Help );
	keyMap.insert(SDLK_PRINT, Qt::Key_Print );
	keyMap.insert(SDLK_SYSREQ, Qt::Key_SysReq );
	keyMap.insert(SDLK_BREAK, Qt::Key_Pause );
	keyMap.insert(SDLK_MENU, Qt::Key_Menu );
	keyMap.insert(SDLK_POWER, Qt::Key_unknown );
	keyMap.insert(SDLK_EURO, Qt::Key_unknown );
	keyMap.insert(SDLK_UNDO, Qt::Key_Undo );
	keyMap.insert(SDLK_LAST, Qt::Key_unknown );

	keyModMap.clear();
	keyModMap.insert(SDLK_UNKNOWN, Qt::NoModifier);
	keyModMap.insert(SDLK_FIRST, Qt::NoModifier);
	keyModMap.insert(SDLK_BACKSPACE, Qt::NoModifier);
	keyModMap.insert(SDLK_TAB, Qt::NoModifier);
	keyModMap.insert(SDLK_CLEAR, Qt::NoModifier);
	keyModMap.insert(SDLK_RETURN, Qt::NoModifier);
	keyModMap.insert(SDLK_PAUSE, Qt::NoModifier);
	keyModMap.insert(SDLK_ESCAPE, Qt::NoModifier);
	keyModMap.insert(SDLK_SPACE, Qt::NoModifier);
	keyModMap.insert(SDLK_EXCLAIM, Qt::NoModifier);
	keyModMap.insert(SDLK_QUOTEDBL, Qt::NoModifier);
	keyModMap.insert(SDLK_HASH, Qt::NoModifier);
	keyModMap.insert(SDLK_DOLLAR, Qt::NoModifier);
	keyModMap.insert(SDLK_AMPERSAND, Qt::NoModifier);
	keyModMap.insert(SDLK_QUOTE, Qt::NoModifier);
	keyModMap.insert(SDLK_LEFTPAREN, Qt::NoModifier);
	keyModMap.insert(SDLK_RIGHTPAREN, Qt::NoModifier);
	keyModMap.insert(SDLK_ASTERISK, Qt::NoModifier);
	keyModMap.insert(SDLK_PLUS, Qt::NoModifier);
	keyModMap.insert(SDLK_COMMA, Qt::NoModifier);
	keyModMap.insert(SDLK_MINUS, Qt::NoModifier);
	keyModMap.insert(SDLK_PERIOD, Qt::NoModifier);
	keyModMap.insert(SDLK_SLASH, Qt::NoModifier);
	keyModMap.insert(SDLK_0, Qt::NoModifier);
	keyModMap.insert(SDLK_1, Qt::NoModifier);
	keyModMap.insert(SDLK_2, Qt::NoModifier);
	keyModMap.insert(SDLK_3, Qt::NoModifier);
	keyModMap.insert(SDLK_4, Qt::NoModifier);
	keyModMap.insert(SDLK_5, Qt::NoModifier);
	keyModMap.insert(SDLK_6, Qt::NoModifier);
	keyModMap.insert(SDLK_7, Qt::NoModifier);
	keyModMap.insert(SDLK_8, Qt::NoModifier);
	keyModMap.insert(SDLK_9, Qt::NoModifier);
	keyModMap.insert(SDLK_COLON, Qt::NoModifier);
	keyModMap.insert(SDLK_SEMICOLON, Qt::NoModifier);
	keyModMap.insert(SDLK_LESS, Qt::NoModifier);
	keyModMap.insert(SDLK_EQUALS, Qt::NoModifier);
	keyModMap.insert(SDLK_GREATER, Qt::NoModifier);
	keyModMap.insert(SDLK_QUESTION, Qt::NoModifier);
	keyModMap.insert(SDLK_AT, Qt::NoModifier);
	keyModMap.insert(SDLK_LEFTBRACKET, Qt::NoModifier);
	keyModMap.insert(SDLK_BACKSLASH, Qt::NoModifier);
	keyModMap.insert(SDLK_RIGHTBRACKET, Qt::NoModifier);
	keyModMap.insert(SDLK_CARET, Qt::NoModifier);
	keyModMap.insert(SDLK_UNDERSCORE, Qt::NoModifier);
	keyModMap.insert(SDLK_BACKQUOTE, Qt::NoModifier);
	keyModMap.insert(SDLK_a, Qt::NoModifier);
	keyModMap.insert(SDLK_b, Qt::NoModifier);
	keyModMap.insert(SDLK_c, Qt::NoModifier);
	keyModMap.insert(SDLK_d, Qt::NoModifier);
	keyModMap.insert(SDLK_e, Qt::NoModifier);
	keyModMap.insert(SDLK_f, Qt::NoModifier);
	keyModMap.insert(SDLK_g, Qt::NoModifier);
	keyModMap.insert(SDLK_h, Qt::NoModifier);
	keyModMap.insert(SDLK_i, Qt::NoModifier);
	keyModMap.insert(SDLK_j, Qt::NoModifier);
	keyModMap.insert(SDLK_k, Qt::NoModifier);
	keyModMap.insert(SDLK_l, Qt::NoModifier);
	keyModMap.insert(SDLK_m, Qt::NoModifier);
	keyModMap.insert(SDLK_n, Qt::NoModifier);
	keyModMap.insert(SDLK_o, Qt::NoModifier);
	keyModMap.insert(SDLK_p, Qt::NoModifier);
	keyModMap.insert(SDLK_q, Qt::NoModifier);
	keyModMap.insert(SDLK_r, Qt::NoModifier);
	keyModMap.insert(SDLK_s, Qt::NoModifier);
	keyModMap.insert(SDLK_t, Qt::NoModifier);
	keyModMap.insert(SDLK_u, Qt::NoModifier);
	keyModMap.insert(SDLK_v, Qt::NoModifier);
	keyModMap.insert(SDLK_w, Qt::NoModifier);
	keyModMap.insert(SDLK_x, Qt::NoModifier);
	keyModMap.insert(SDLK_y, Qt::NoModifier);
	keyModMap.insert(SDLK_z, Qt::NoModifier);
	keyModMap.insert(SDLK_DELETE, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_0, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_1, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_2, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_3, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_4, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_5, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_6, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_7, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_8, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_9, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_10, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_11, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_12, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_13, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_14, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_15, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_16, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_17, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_18, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_19, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_20, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_21, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_22, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_23, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_24, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_25, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_26, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_27, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_28, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_29, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_30, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_31, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_32, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_33, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_34, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_35, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_36, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_37, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_38, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_39, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_40, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_41, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_42, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_43, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_44, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_45, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_46, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_47, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_48, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_49, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_50, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_51, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_52, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_53, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_54, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_55, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_56, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_57, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_58, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_59, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_60, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_61, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_62, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_63, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_64, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_65, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_66, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_67, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_68, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_69, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_70, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_71, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_72, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_73, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_74, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_75, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_76, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_77, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_78, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_79, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_80, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_81, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_82, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_83, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_84, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_85, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_86, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_87, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_88, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_89, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_90, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_91, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_92, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_93, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_94, Qt::NoModifier);
	keyModMap.insert(SDLK_WORLD_95, Qt::NoModifier);
	keyModMap.insert(SDLK_KP0, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP1, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP2, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP3, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP4, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP5, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP6, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP7, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP8, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP9, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP_PERIOD, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP_DIVIDE, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP_MULTIPLY, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP_MINUS, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP_PLUS, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP_ENTER, Qt::KeypadModifier);
	keyModMap.insert(SDLK_KP_EQUALS, Qt::KeypadModifier);
	keyModMap.insert(SDLK_UP, Qt::NoModifier);
	keyModMap.insert(SDLK_DOWN, Qt::NoModifier);
	keyModMap.insert(SDLK_RIGHT, Qt::NoModifier);
	keyModMap.insert(SDLK_LEFT, Qt::NoModifier);
	keyModMap.insert(SDLK_INSERT, Qt::NoModifier);
	keyModMap.insert(SDLK_HOME, Qt::NoModifier);
	keyModMap.insert(SDLK_END, Qt::NoModifier);
	keyModMap.insert(SDLK_PAGEUP, Qt::NoModifier);
	keyModMap.insert(SDLK_PAGEDOWN, Qt::NoModifier);
	keyModMap.insert(SDLK_F1, Qt::NoModifier);
	keyModMap.insert(SDLK_F2, Qt::NoModifier);
	keyModMap.insert(SDLK_F3, Qt::NoModifier);
	keyModMap.insert(SDLK_F4, Qt::NoModifier);
	keyModMap.insert(SDLK_F5, Qt::NoModifier);
	keyModMap.insert(SDLK_F6, Qt::NoModifier);
	keyModMap.insert(SDLK_F7, Qt::NoModifier);
	keyModMap.insert(SDLK_F8, Qt::NoModifier);
	keyModMap.insert(SDLK_F9, Qt::NoModifier);
	keyModMap.insert(SDLK_F10, Qt::NoModifier);
	keyModMap.insert(SDLK_F11, Qt::NoModifier);
	keyModMap.insert(SDLK_F12, Qt::NoModifier);
	keyModMap.insert(SDLK_F13, Qt::NoModifier);
	keyModMap.insert(SDLK_F14, Qt::NoModifier);
	keyModMap.insert(SDLK_F15, Qt::NoModifier);
	keyModMap.insert(SDLK_NUMLOCK, Qt::KeypadModifier);
	keyModMap.insert(SDLK_CAPSLOCK, Qt::NoModifier);
	keyModMap.insert(SDLK_SCROLLOCK, Qt::NoModifier);
	keyModMap.insert(SDLK_RSHIFT, Qt::ShiftModifier);
	keyModMap.insert(SDLK_LSHIFT, Qt::ShiftModifier);
	keyModMap.insert(SDLK_RCTRL, Qt::ControlModifier);
	keyModMap.insert(SDLK_LCTRL, Qt::ControlModifier);
	keyModMap.insert(SDLK_RALT, Qt::AltModifier);
	keyModMap.insert(SDLK_LALT, Qt::AltModifier);
	keyModMap.insert(SDLK_RMETA, Qt::NoModifier);
	keyModMap.insert(SDLK_LMETA, Qt::NoModifier);
	keyModMap.insert(SDLK_LSUPER, Qt::NoModifier);
	keyModMap.insert(SDLK_RSUPER, Qt::NoModifier);
	keyModMap.insert(SDLK_MODE, Qt::NoModifier);
	keyModMap.insert(SDLK_COMPOSE, Qt::NoModifier);
	keyModMap.insert(SDLK_HELP, Qt::NoModifier);
	keyModMap.insert(SDLK_PRINT, Qt::NoModifier);
	keyModMap.insert(SDLK_SYSREQ, Qt::NoModifier);
	keyModMap.insert(SDLK_BREAK, Qt::NoModifier);
	keyModMap.insert(SDLK_MENU, Qt::NoModifier);
	keyModMap.insert(SDLK_POWER, Qt::NoModifier);
	keyModMap.insert(SDLK_EURO, Qt::NoModifier);
	keyModMap.insert(SDLK_UNDO, Qt::NoModifier);
	keyModMap.insert(SDLK_LAST, Qt::NoModifier);

	modMap.clear();
	modMap.insert(KMOD_NONE, Qt::NoModifier );
	modMap.insert(KMOD_LSHIFT, Qt::ShiftModifier );
	modMap.insert(KMOD_RSHIFT, Qt::ShiftModifier );
	modMap.insert(KMOD_LCTRL, Qt::ControlModifier );
	modMap.insert(KMOD_RCTRL, Qt::ControlModifier );
	modMap.insert(KMOD_LALT, Qt::AltModifier );
	modMap.insert(KMOD_RALT, Qt::AltModifier );
	modMap.insert(KMOD_LMETA, Qt::MetaModifier );
	modMap.insert(KMOD_RMETA, Qt::MetaModifier );
	modMap.insert(KMOD_NUM, Qt::KeypadModifier );
	modMap.insert(KMOD_CAPS, Qt::NoModifier );
	modMap.insert(KMOD_MODE, Qt::NoModifier );
	modMap.insert(KMOD_RESERVED, Qt::NoModifier );
}

Qt::Key QSdlKeyboardMap::getQtKey(SDLKey key){
	return this->keyMap.value(key, Qt::Key_unknown);
}

Qt::KeyboardModifiers QSdlKeyboardMap::getQtModifier(SDLKey key, SDLMod mod){
	Qt::KeyboardModifier qmod = this->keyModMap.value(key, Qt::NoModifier);
	if(mod == KMOD_NONE){
		return qmod;
	}else{
		return this->modMap.value(mod, Qt::NoModifier);
	}
}
